project_id = "xnveugycurplszevdxtw"

[functions.loxone-api]
verify_jwt = false

[functions.loxone-websocket]
verify_jwt = false

[functions.send-invitation-email]
verify_jwt = false

[functions.meter-ocr]
verify_jwt = false

[functions.ocpp-central]
verify_jwt = false

[functions.activate-invited-user]
verify_jwt = false

[functions.send-charging-invoices]
verify_jwt = false
