project_id = "xnveugycurplszevdxtw"

[functions.ingest-node-metrics]
verify_jwt = false

[functions.community-marketplace-public]
verify_jwt = false

[functions.charge-point-auto-reboot]
verify_jwt = false
