REVOKE EXECUTE ON FUNCTION public.has_role(uuid, app_role) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.has_permission(uuid, text) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.has_location_access(uuid, uuid) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.is_own_profile(uuid) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_user_tenant_id() FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_auth_user_email() FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_location_main_meter(uuid) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_meter_daily_totals(uuid[], date, date) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_meter_period_sums(uuid[], date, date) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_power_readings_5min(uuid[], timestamptz, timestamptz) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_pv_actual_hourly(uuid, timestamptz, timestamptz) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_pv_actual_hourly_all(uuid, timestamptz, timestamptz) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_pv_actual_daily_sums(uuid, date, date) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_pv_actual_daily_sums_all(uuid, date, date) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_pv_forecast_daily_sums(uuid, date, date) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_pv_forecast_daily_sums_all(uuid, date, date) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_pv_forecast_daily_compare(uuid, date, date) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_pv_forecast_daily_compare_all(uuid, date, date) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_charge_point_uptime_pct(uuid, integer) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.bootstrap_user_role() FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.ensure_at_least_one_admin() FROM anon, PUBLIC;