INSERT INTO charger_models (vendor, model, protocol, notes, is_active) VALUES
  ('ABB', 'Terra AC W7-T-RD-M', 'ocpp1.6', 'SIM/LAN, FW >= 1.6.6 empfohlen', true),
  ('ABB', 'Terra AC W11-T-RD-M', 'ocpp1.6', 'SIM/LAN, FW >= 1.6.6 empfohlen', true),
  ('ABB', 'Terra AC W22-T-RD-M', 'ocpp1.6', 'SIM/LAN, FW >= 1.6.6 empfohlen', true),
  ('Alfen', 'Eve Single S-Line', 'ocpp1.6', 'LAN/SIM, Smart Charging faehig', true),
  ('Alfen', 'Eve Single Pro-Line', 'ocpp1.6', 'LAN/SIM, MID-Zaehler optional', true),
  ('Alfen', 'Eve Double Pro-Line', 'ocpp1.6', 'Dual-Socket, Load Balancing', true),
  ('Easee', 'Home', 'ocpp1.6', 'Cloud-OCPP, Aktivierung ueber Easee Portal', true),
  ('Easee', 'Charge', 'ocpp1.6', 'Cloud-OCPP, Aktivierung ueber Easee Portal', true),
  ('EVBox', 'Elvi', 'ocpp1.6', 'WiFi/LAN, Konfiguration ueber EVSE-Portal', true),
  ('EVBox', 'BusinessLine', 'ocpp1.6', 'LAN/SIM, fuer gewerblichen Einsatz', true),
  ('go-e', 'Charger Gemini', 'ocpp1.6', 'WiFi, Konfiguration ueber go-e App', true),
  ('go-e', 'Charger Gemini Flex', 'ocpp1.6', 'Mobile Variante, WiFi', true),
  ('Heidelberg', 'Energy Control', 'ocpp1.6', 'Benoetigt externen OCPP-Gateway', true),
  ('KEBA', 'KeContact P30 x-series', 'ocpp1.6', 'LAN, Master-faehig fuer c-series', true),
  ('KEBA', 'KeContact P30 c-series', 'ocpp1.6', 'Nur als Slave ueber x-series Master', true),
  ('Mennekes', 'Amtron Charge Control', 'ocpp1.6', 'LAN, eichrechtskonform moeglich', true),
  ('Mennekes', 'Amtron Xtra 11/22', 'ocpp1.6', 'LAN/SIM', true),
  ('NRGkick', 'NRGkick Smart', 'ocpp1.6', 'Mobile Wallbox, WiFi, OCPP ueber App aktivieren', true),
  ('Schneider Electric', 'EVlink Pro AC', 'ocpp1.6', 'LAN/SIM, Smart Charging', true),
  ('Wallbox', 'Pulsar Plus', 'ocpp1.6', 'WiFi/BT, OCPP ueber myWallbox Portal', true),
  ('Wallbox', 'Pulsar Pro', 'ocpp1.6', 'WiFi/BT/LAN, Power Sharing', true),
  ('Wallbox', 'Commander 2', 'ocpp1.6', 'Touchscreen, WiFi/LAN/SIM', true),
  ('Webasto', 'Unite', 'ocpp1.6', 'LAN/SIM, MID-Zaehler integriert', true),
  ('Webasto', 'Live', 'ocpp1.6', 'WiFi/LAN', true),
  ('Zaptec', 'Go', 'ocpp1.6', 'Aktivierung ueber Zaptec Portal erforderlich', true),
  ('Zaptec', 'Pro', 'ocpp1.6', 'LAN/SIM, fuer gewerblichen Einsatz', true),
  ('DUOSIDA', 'DSD1-EU 7kW', 'ocpp1.6', 'ws:// nutzen, nur 2.4 GHz WiFi, Heartbeat 30s empfohlen', true),
  ('DUOSIDA', 'DSD1-EU 22kW', 'ocpp1.6', 'ws:// nutzen, nur 2.4 GHz WiFi, Heartbeat 30s empfohlen', true);