REVOKE EXECUTE ON FUNCTION public.aggregate_pv_actual_hourly(timestamptz, timestamptz) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.auto_resolve_integration_errors_on_sync_success() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.check_main_meter_no_parent() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.check_meter_hierarchy() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.cleanup_charge_point_uptime_snapshots() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.cleanup_expired_backups() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.cleanup_old_infra_metrics() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.cleanup_old_ocpp_logs() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.collect_db_metrics() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.compact_power_readings_day(date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.compute_daily_totals_from_5min(date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.create_task_for_integration_error() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.enforce_simulator_instance_limit() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.ensure_single_main_location() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.generate_app_tag() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.guard_privileged_roles() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.handle_new_user_role() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.log_user_role_change() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.resolve_task_for_integration_error() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.snapshot_charge_point_uptime() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.sync_meter_room_from_sensor_position() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.clear_meter_room_on_sensor_delete() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.charge_points_clear_password_when_no_auth() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.update_updated_at_column() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.try_acquire_gateway_refresh_lock(uuid, text, integer) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.release_gateway_refresh_lock(uuid, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.next_charging_invoice_number(uuid, integer) FROM PUBLIC;