services:

  kong:
    ports: !reset []
    environment:
      KONG_PORT_MAPS: "443:8000,443:8443"

  caddy:
    container_name: supabase-caddy
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    depends_on:
      kong:
        condition: service_healthy
      frontend:
        condition: service_started
    environment:
      APP_DOMAIN: ${APP_DOMAIN}
      API_DOMAIN: ${API_DOMAIN}
    command: caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
    volumes:
      - ./proxy/caddy:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
